### ISSUE TITLE
Build and deploy Deb packages

### ISSUE THREAD

**Issue by marayl** [reactivemarkets/toolbox-cpp#12]
Build Deb package using CPack and integrate with CircleCI, so that the package is deployed as a GitHub release artefact.

Our custom toolchain image uses:

- Boost 1.67.0
- Clang 7.0.1
- GCC 8.3

We might be able to lower the requirements to 1.63.0, but I have not tried.

I don't reason any reason not to keep the RPM and, although we don't use it, it may have wider appeal.

Regarding CircleCI, I double-checked the YML file and it will upload all artefacts in build/dist, so it should work without change.

**Comment by marayl** [comment]
Our custom toolchain image uses:

- Boost 1.67.0
- Clang 7.0.1
- GCC 8.3

We might be able to lower the requirements to 1.63.0, but I have not tried.

I don't reason any reason not to keep the RPM and, although we don't use it, it may have wider appeal.

Regarding CircleCI, I double-checked the YML file and it will upload all artefacts in build/dist, so it should work without change.

**Comment by rfernandes** [comment]
Regarding the specific versions of boost / debian we have:
Stretch(9 - stable) - 1.62
Buster (experimental) - 1.67

Might as well target buster, I'll update the CMakeLists.txt as well.
